import BottomNav from "@/components/bottomnav/bottomnav";
import "./globals.css";

export const metadata = {
  title: "my session",
  description: "Generated by create next app",
  icons: {
    apple: [{ url: "/favicon/apple-touch-icon.png" }],
  },
  appleTouchIcon: "/favicon/apple-touch-icon.png",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
  },
};

export const viewport = {
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={"antialiased dark"}>
        {children}
        <BottomNav />
      </body>
    </html>
  );
}
